version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-react-app
    ports:
      - "1323:1323"
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=1323
      - DATABASE_DRIVER=sqlite
      - DATABASE_DSN=./data.db
      - SESSION_SECRET=your-secret-key
    volumes:
      # 挂载数据库文件（如果使用 SQLite）
      - ./data:/app/data
      # 挂载日志目录（可选）
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:1323/api/v1/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # 可选：添加数据库服务（如果不使用 SQLite）
  # postgres:
  #   image: postgres:15-alpine
  #   container_name: go-react-postgres
  #   environment:
  #     POSTGRES_DB: go_react_db
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   restart: unless-stopped

  # mysql:
  #   image: mysql:8.0
  #   container_name: go-react-mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: rootpassword
  #     MYSQL_DATABASE: go_react_db
  #     MYSQL_USER: user
  #     MYSQL_PASSWORD: password
  #   volumes:
  #     - mysql_data:/var/lib/mysql
  #   ports:
  #     - "3306:3306"
  #   restart: unless-stopped

volumes:
  # postgres_data:
  # mysql_data:
  data:
  logs:

networks:
  default:
    name: go-react-network
